services:
  # V.H.A.C.K. Web Interface - Default Service
  vhack:
    image: vhack-web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vhack-web
    environment:
      - PORT=8000
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    ports:
      - "8000:8000"
    command: ["poetry", "run", "python", "vhack.py", "--web"]
    restart: unless-stopped