name: Analyze Repo Only

on:
  workflow_call:
    inputs:
      scanner_model:
        required: true
        type: string
      repo_path:
        required: false
        type: string
        default: "../"
      exclude_path:
        required: false
        type: string
        default: "../vulnerability-scanner-rs"
    secrets:
      OPENROUTER_API_KEY:
        required: true

jobs:
  build-rust:
    uses: ./.github/workflows/build-rust.yml

  analyze-repo:
    needs: build-rust
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache restore rust build target
      uses: actions/cache/restore@v4
      with:
        path: vulnerability-scanner-rs/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('vulnerability-scanner-rs/src/**/*.rs') }}

    - name: Analyze repo
      run: |
        cd vulnerability-scanner-rs
        ./target/release/vulnerability-scanner-rs --analyze-repo --repo-path ${{ inputs.repo_path }} --exclude-path ${{ inputs.exclude_path }} --provider openrouter --model ${{ inputs.scanner_model }} --api-max-retries 3 --max-tokens 10000
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    - name: Upload repo-analysis.md as artifact
      uses: actions/upload-artifact@v4
      with:
        name: repo-analysis
        path: vulnerability-scanner-rs/repo-analysis.md