name: Generate prompts with Mistral-7B-Instruct

on:
  # push:
  #   branches: [main, build-action]
  workflow_dispatch:

jobs:
  generate:
    uses: ./.github/workflows/generate-prompts-only.yml
    with:
      scanner_model: mistralai/mistral-7b-instruct
    secrets:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}