name: Generate And Test Prompts

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - build-action

jobs:
  generate-prompts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      runid: ${{github.run_id}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Build vulnerability-scanner-rs
      run: |
        cd vulnerability-scanner-rs
        cargo build --release

    - name: Generate prompts
      run: |
        cd vulnerability-scanner-rs
        ./target/release/vulnerability-scanner-rs --generate-prompts --concurrency 4
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Upload prompts.csv as artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-prompts
        path: vulnerability-scanner-rs/prompts.csv

    - name: Upload testcategories.md as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-categories
        path: vulnerability-scanner-rs/testcategories.md

    - name: Cache save rust build target
      id: cache-target-save
      uses: actions/cache/save@v4
      with:
        path: vulnerability-scanner-rs/target
        key: vulnerability-scanner-target-${{github.run_id}}



  test-prompts:
    needs: generate-prompts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add mask
      run: |
        echo "::add-mask::${{ secrets.OPENROUTER_API_KEY }}"

    - name: Prepare config
      run: |
        cp config.example.yaml config.yaml
        sed -i 's/your_openrouter_api_key_here/${{ secrets.OPENROUTER_API_KEY }}/' config.yaml
        sed -i 's/z-ai\/glm-4.5-air:free/z-ai\/glm-4-32b/' config.yaml

    - name: Download prompts artifact
      uses: actions/download-artifact@v4
      with:
        name: generated-prompts
        path: vulnerability-scanner-rs

    - name: Download test-categories artifact
      uses: actions/download-artifact@v4
      with:
        name: test-categories
        path: vulnerability-scanner-rs

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Cache restore rust build target
      id: cache-target-restore
      uses: actions/cache/restore@v4
      with:
        path: vulnerability-scanner-rs/target
        key: vulnerability-scanner-target-${{needs.generate-prompts.outputs.runid}}

    - name: Start VHACK service
      run: docker compose up --build -d

    - name: Wait for VHACK service to be ready
      run: |
        timeout 300 bash -c 'until curl -f http://localhost:8000/; do sleep 5; done'

    - name: Run vulnerability-scanner-rs with parallelism
      run: |
        cd vulnerability-scanner-rs
        ./target/release/vulnerability-scanner-rs \
          --concurrency 4 \
          --timeout-ms 600000 \
          --target http://localhost:8000 \
          --prompts prompts.csv \
          --out results.jsonl
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-scanner-results
        path: |
          vulnerability-scanner-rs/results.jsonl
          vulnerability-scanner-rs/summary.md

    - name: Stop VHACK service
      run: docker compose down


      
  evaluate-results:
    needs: test-prompts
    runs-on: ubuntu-latest
    steps:
      - name: Download results artifact
        uses: actions/download-artifact@v4
        with:
          name: vulnerability-scanner-results
          path: results

      - name: Evaluate summary.md
        run: |
          cd results
          # Extract time elapsed in seconds
          TIME_ELAPSED=$(grep "Total time elapsed:" summary.md | sed 's/.*: \([0-9.]*\) seconds.*/\1/')
          # Extract worked prompts count
          WORKED_PROMPTS=$(grep "**Worked Prompts:**" summary.md | sed 's/.*: \([0-9]*\).*/\1/')
          
          # Check conditions
          if (( $(echo "$TIME_ELAPSED > 600" | bc -l) )) || (( WORKED_PROMPTS < 5 )); then
            echo "Evaluation failed: Time elapsed ($TIME_ELAPSED s > 600 s) or Worked prompts ($WORKED_PROMPTS < 5)"
            exit 1
          else
            echo "Evaluation passed: Time elapsed $TIME_ELAPSED s, Worked prompts $WORKED_PROMPTS"
          fi