name: Generate Prompts Only

on:
  workflow_call:
    inputs:
      scanner_model:
        required: true
        type: string
      tool_analysis_run_id:
        required: false
        type: string
      tool_analysis_artifact:
        required: false
        type: string
        default: "test-categories"
    secrets:
      OPENROUTER_API_KEY:
        required: true

jobs:
  build-rust:
    uses: ./.github/workflows/build-rust.yml

  generate-prompts:
    needs: build-rust
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache restore rust build target
      uses: actions/cache/restore@v4
      with:
        path: vulnerability-scanner-rs/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('vulnerability-scanner-rs/src/**/*.rs') }}

    - name: Download testcategories artifact
      if: inputs.tool_analysis_run_id != ''
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.tool_analysis_artifact }}
        path: vulnerability-scanner-rs/
        run-id: ${{ inputs.tool_analysis_run_id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate prompts
      run: |
        cd vulnerability-scanner-rs
        ./target/release/vulnerability-scanner-rs --generate-prompts --concurrency 4 --provider openrouter --model ${{ inputs.scanner_model }} --api-max-retries 3 --max-tokens 4000
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    - name: Upload prompts.csv as artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-prompts
        path: vulnerability-scanner-rs/prompts.csv

    - name: Upload testcategories.md as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-categories
        path: vulnerability-scanner-rs/testcategories.md