name: Generate Prompts from Tool Analysis

on:
  workflow_call:
    inputs:
      scanner_model:
        required: true
        type: string
      tool_analysis_artifact:
        required: false
        type: string
        default: "test-categories"
      tool_analysis_run_id:
        required: true
        type: string
    secrets:
      OPENROUTER_API_KEY:
        required: true

jobs:
  generate-prompts:
    uses: ./.github/workflows/generate-prompts.yml
    with:
      scanner_model: ${{ inputs.scanner_model }}
      tool_analysis_run_id: ${{ inputs.tool_analysis_run_id }}
      tool_analysis_artifact: ${{ inputs.tool_analysis_artifact }}
    secrets:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}