name: "ministral-8b -vs-> llama-3.2-3b-instruct"

on:
  workflow_run:
    workflows: ["Generate Prompts for Ministral-8B"]
    types: [completed]

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/test-prompts.yml
    with:
      scanner_model: mistralai/ministral-8b
      vhack_model: meta-llama/llama-3.2-3b-instruct
      generate_run_id: ${{ github.event.workflow_run.id }}
    secrets:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}